const WorkoutActionTypes = {
  WORKOUT_RESET: "WORKOUT_RESET",
  SET_ADD: "SET_ADD",
  SET_REMOVE: "SET_REMOVE",
  SET_COMPLETE: "SET_COMPLETE",
  EXERCISE_ADD: "ADD_EXERCISE",
  EXERCISE_REMOVE: "REMOVE_EXERCISE",
  EXERCISE_RESET: "EXERCISE_RESET",
  WORKOUT_SAVE: "WORKOUT_SAVE",
  TIMELINE_SHOW: "TIMELINE_SHOW",
};

export default WorkoutActionTypes;
